name: publishPage
run-name: Publish Page

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 20

            - name: Install Dependencies
              run: npm ci

            - name: Configure Git
              run: |
                  git config --global user.email "you@example.com"
                  git config --global user.name "Your Name"

            - name: Delete gh-pages branch
              run: |
                  git branch -D gh-pages || true
                  git push origin --delete gh-pages || true

            - name: Publish Page
              env:
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
              run: |
                  git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/JuanDVejarano/page-herjep.git
                  npm run deploy
